language: python
cache: pip

python: 3.6

env:
  - TOX="tests"
  - TOX="docs"

install:
  - pip install tox-travis python-coveralls
script:
  - tox
after_success:
  - test $TOX = "tests" && coveralls

deploy:
  skip-cleanup: true
  on:
    tags: true
    condition: $TOX = "docs"

  - provider: releases
    api_key: $GITHUB_TOKEN

  - provider: pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: .tox/docs/_build
