language: python
cache: pip

python: 3.6

env:
  - TOX="tests"
  - TOX="docs"
  - TOX="linter"

install:
  - pip install tox-travis
script:
  - tox
after_success:
  - test $TOX = "tests" && pip install python-coveralls && coveralls

deploy:
  - provider: pypi
    user: seignovert
    password:
      secure: 15qNERDqwRGYsT0O++eXBAimzsIjI+RLSBNtzV+V74q4Jv6bJwu9ZNeYr3BERs3vBiwTGkVVohGb72ok8wJvdGOrZDefDdhUL/LSoQaXB+m76g53uZQZT5mpMskMDhWYiAkNcGj8XT37DsA8r4ik3z7RRqsQDR2iQnH8r9iqxhU33FOSfg0mDekRqw9aHKy030f5xiTwWg12ZYTjbrriOi/idXSjIEs/a6nEEJ1n6LoZsigVh0Hn4adIxljJ/IKRbRzN5BCgppoV7Qc5Tvqr+hTHPKjN306ZFFN3uF2vkGTkJRtg5uvcMDJAg/KjS7jVHDrqNbns/faFxNpPDckeGk067MUr880es8ah4sXGEyRyTSozwr8UVphiorHQDDfIC+bm9P96URe6Dfo2x3c16uvUwqcgH4IDfNoZEq3YBaKjC7quQukExl/f+nViUL+JUJWeeNoOicbocjd5862EoXdL9VHWLHTIJRAxzrBJd0uCi/Zv0R+kkXVMPCPlkYnyKQRnSOgvpjjnAhDNXT8wMvMxv8tBLNQjNRgxsknr9kgWQ1O1aRhDzJiki0dZ2pav56hMNnFVXyO90AsCfEtcQ35CYpvFdqhSuJvfSr/E5s41WUbMErSGhUz3Pny5ccgRb/GgRwuetxwVSJUmq0q7frfqNsa/NjwhvC3e1yAK2Gg=
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip-cleanup: true
    on:
      tags: true
      condition: $TOX = "tests"

  - provider: releases
    name: Version $TRAVIS_TAG
    api_key:
      secure: G4oM7U54hyXF4JBmSB1Jf6gwiCQVFoXS/PGMT9AwqWqoY0VcNTc6IQM0Wn1tkPa0zsbUbSC3M3PtLHBD1mlAvyAYiUHVEbkarRq2cF3SfnDeqcCDv/D8mfymfTDJMCcvcHbhMu2qTLEswNWtaQ+qK9NOEb6db9N4HhAzzU8tMgimyTnk3/wvgmk6k8gR1bq718vDWA5YuYX7AXI3oaeozpAFIIEWT4OumVhTGTlsILkMAeTmxp/ValoT9+BHVaPXYEqKmBL6n3rAtl3WU53SVM3T3cEScDqqkCbCjm7etty2dqP/aJwFaIYx7WXvYfxy4PWbCJsveF172+xH8wEF+sGc/ts/Rygc+OSE7gYjoyvKhsD41D5rqmlxP0UNiMSI5CdNLQHe59clEUHeTxKvQWQ1FsVoFJWmfwFH/M8kIG2T7P3WppJBxik8pposa7+sn+ehdJCQ5P3MvRlR0PVrXO5XB6PlkmvwhGf0t88fRaFt7A3xXivUmbXAfthKL3tFBmPrbIiYW5Fh/dbyI/IUr8/8x0jo5uJjUpcuYSvXOqzcpaJJ6OSfM28sLdf1OYZtZdTCXWMZYZ9IqffccLbAoyaTY/JH6LdbJDZHcUjxhyypjEuBX8YeJQmJpSYxyKbDiQi5/ImwV1mwwIJLwgfSHJRsUtxjCbZE5sGMvhodnF4=
    skip-cleanup: true
    on:
      tags: true
      condition: $TOX = "docs"

  - provider: pages
    github-token:
      secure: G4oM7U54hyXF4JBmSB1Jf6gwiCQVFoXS/PGMT9AwqWqoY0VcNTc6IQM0Wn1tkPa0zsbUbSC3M3PtLHBD1mlAvyAYiUHVEbkarRq2cF3SfnDeqcCDv/D8mfymfTDJMCcvcHbhMu2qTLEswNWtaQ+qK9NOEb6db9N4HhAzzU8tMgimyTnk3/wvgmk6k8gR1bq718vDWA5YuYX7AXI3oaeozpAFIIEWT4OumVhTGTlsILkMAeTmxp/ValoT9+BHVaPXYEqKmBL6n3rAtl3WU53SVM3T3cEScDqqkCbCjm7etty2dqP/aJwFaIYx7WXvYfxy4PWbCJsveF172+xH8wEF+sGc/ts/Rygc+OSE7gYjoyvKhsD41D5rqmlxP0UNiMSI5CdNLQHe59clEUHeTxKvQWQ1FsVoFJWmfwFH/M8kIG2T7P3WppJBxik8pposa7+sn+ehdJCQ5P3MvRlR0PVrXO5XB6PlkmvwhGf0t88fRaFt7A3xXivUmbXAfthKL3tFBmPrbIiYW5Fh/dbyI/IUr8/8x0jo5uJjUpcuYSvXOqzcpaJJ6OSfM28sLdf1OYZtZdTCXWMZYZ9IqffccLbAoyaTY/JH6LdbJDZHcUjxhyypjEuBX8YeJQmJpSYxyKbDiQi5/ImwV1mwwIJLwgfSHJRsUtxjCbZE5sGMvhodnF4=
    keep-history: true
    local-dir: .tox/docs/_build
    skip-cleanup: true
    on:
      tags: true
      condition: $TOX = "docs"
